// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approval_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApprovalRequest = `-- name: CreateApprovalRequest :one
INSERT INTO approval_requests (
    project_id, requested_by, resource_type, request_payload,
    reasons, matched_policies, status, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, requested_by, resource_type, request_payload, reasons, matched_policies, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at
`

type CreateApprovalRequestParams struct {
	ProjectID       string             `json:"project_id"`
	RequestedBy     string             `json:"requested_by"`
	ResourceType    string             `json:"resource_type"`
	RequestPayload  []byte             `json:"request_payload"`
	Reasons         []byte             `json:"reasons"`
	MatchedPolicies []byte             `json:"matched_policies"`
	Status          string             `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, createApprovalRequest,
		arg.ProjectID,
		arg.RequestedBy,
		arg.ResourceType,
		arg.RequestPayload,
		arg.Reasons,
		arg.MatchedPolicies,
		arg.Status,
		arg.ExpiresAt,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RequestedBy,
		&i.ResourceType,
		&i.RequestPayload,
		&i.Reasons,
		&i.MatchedPolicies,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewComment,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireApprovalRequests = `-- name: ExpireApprovalRequests :execrows
UPDATE approval_requests
SET status = 'expired', updated_at = now()
WHERE status = 'pending' AND expires_at < now()
`

func (q *Queries) ExpireApprovalRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireApprovalRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApprovalRequest = `-- name: GetApprovalRequest :one
SELECT id, project_id, requested_by, resource_type, request_payload, reasons, matched_policies, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at FROM approval_requests WHERE id = $1
`

func (q *Queries) GetApprovalRequest(ctx context.Context, id string) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getApprovalRequest, id)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RequestedBy,
		&i.ResourceType,
		&i.RequestPayload,
		&i.Reasons,
		&i.MatchedPolicies,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewComment,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingApprovals = `-- name: ListPendingApprovals :many
SELECT id, project_id, requested_by, resource_type, request_payload, reasons, matched_policies, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at FROM approval_requests
WHERE status = 'pending'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPendingApprovalsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPendingApprovals(ctx context.Context, arg ListPendingApprovalsParams) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listPendingApprovals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequest{}
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RequestedBy,
			&i.ResourceType,
			&i.RequestPayload,
			&i.Reasons,
			&i.MatchedPolicies,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewComment,
			&i.ReviewedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalRequestsByProject = `-- name: ListApprovalRequestsByProject :many
SELECT id, project_id, requested_by, resource_type, request_payload, reasons, matched_policies, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at FROM approval_requests
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListApprovalRequestsByProjectParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListApprovalRequestsByProject(ctx context.Context, arg ListApprovalRequestsByProjectParams) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listApprovalRequestsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequest{}
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RequestedBy,
			&i.ResourceType,
			&i.RequestPayload,
			&i.Reasons,
			&i.MatchedPolicies,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewComment,
			&i.ReviewedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalsByProject = `-- name: ListPendingApprovalsByProject :many
SELECT id, project_id, requested_by, resource_type, request_payload, reasons, matched_policies, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at FROM approval_requests
WHERE project_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingApprovalsByProject(ctx context.Context, projectID string) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequest{}
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RequestedBy,
			&i.ResourceType,
			&i.RequestPayload,
			&i.Reasons,
			&i.MatchedPolicies,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewComment,
			&i.ReviewedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewApprovalRequest = `-- name: ReviewApprovalRequest :one
UPDATE approval_requests
SET status = $2, reviewed_by = $3, review_comment = $4, reviewed_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, project_id, requested_by, resource_type, request_payload, reasons, matched_policies, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at
`

type ReviewApprovalRequestParams struct {
	ID            string  `json:"id"`
	Status        string  `json:"status"`
	ReviewedBy    *string `json:"reviewed_by"`
	ReviewComment string  `json:"review_comment"`
}

func (q *Queries) ReviewApprovalRequest(ctx context.Context, arg ReviewApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, reviewApprovalRequest,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewComment,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RequestedBy,
		&i.ResourceType,
		&i.RequestPayload,
		&i.Reasons,
		&i.MatchedPolicies,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewComment,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
