// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
)

const createAuditEntry = `-- name: CreateAuditEntry :one
INSERT INTO audit_entries (actor_id, project_id, action, target_type, target_id, detail, allowed)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, actor_id, project_id, action, target_type, target_id, detail, allowed, created_at
`

type CreateAuditEntryParams struct {
	ActorID    string  `json:"actor_id"`
	ProjectID  *string `json:"project_id"`
	Action     string  `json:"action"`
	TargetType string  `json:"target_type"`
	TargetID   string  `json:"target_id"`
	Detail     []byte  `json:"detail"`
	Allowed    bool    `json:"allowed"`
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, createAuditEntry,
		arg.ActorID,
		arg.ProjectID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Detail,
		arg.Allowed,
	)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.ProjectID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Detail,
		&i.Allowed,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT id, actor_id, project_id, action, target_type, target_id, detail, allowed, created_at FROM audit_entries
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditEntriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ProjectID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.Allowed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEntriesByActor = `-- name: ListAuditEntriesByActor :many
SELECT id, actor_id, project_id, action, target_type, target_id, detail, allowed, created_at FROM audit_entries
WHERE actor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEntriesByActorParams struct {
	ActorID string `json:"actor_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListAuditEntriesByActor(ctx context.Context, arg ListAuditEntriesByActorParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesByActor, arg.ActorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ProjectID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.Allowed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEntriesByProject = `-- name: ListAuditEntriesByProject :many
SELECT id, actor_id, project_id, action, target_type, target_id, detail, allowed, created_at FROM audit_entries
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEntriesByProjectParams struct {
	ProjectID *string `json:"project_id"`
	Limit     int32   `json:"limit"`
	Offset    int32   `json:"offset"`
}

func (q *Queries) ListAuditEntriesByProject(ctx context.Context, arg ListAuditEntriesByProjectParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ProjectID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.Allowed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
