// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovalRequest struct {
	ID              string             `json:"id"`
	ProjectID       string             `json:"project_id"`
	RequestedBy     string             `json:"requested_by"`
	ResourceType    string             `json:"resource_type"`
	RequestPayload  []byte             `json:"request_payload"`
	Reasons         []byte             `json:"reasons"`
	MatchedPolicies []byte             `json:"matched_policies"`
	Status          string             `json:"status"`
	ReviewedBy      *string            `json:"reviewed_by"`
	ReviewComment   string             `json:"review_comment"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AuditEntry struct {
	ID         string             `json:"id"`
	ActorID    string             `json:"actor_id"`
	ProjectID  *string            `json:"project_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Detail     []byte             `json:"detail"`
	Allowed    bool               `json:"allowed"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	ProjectID string             `json:"project_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Policy struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Scope       string             `json:"scope"`
	ProjectID   *string            `json:"project_id"`
	Enabled     bool               `json:"enabled"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PolicyRule struct {
	ID           string `json:"id"`
	PolicyID     string `json:"policy_id"`
	Description  string `json:"description"`
	ResourceType string `json:"resource_type"`
	Attribute    string `json:"attribute"`
	Operator     string `json:"operator"`
	Value        string `json:"value"`
	Effect       string `json:"effect"`
	Metadata     []byte `json:"metadata"`
}

type Project struct {
	ID          string             `json:"id"`
	TeamID      string             `json:"team_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProvisioningEvent struct {
	ID         string             `json:"id"`
	ResourceID string             `json:"resource_id"`
	Type       string             `json:"type"`
	OldStatus  string             `json:"old_status"`
	NewStatus  string             `json:"new_status"`
	Message    string             `json:"message"`
	Detail     []byte             `json:"detail"`
	ActorID    string             `json:"actor_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Quota struct {
	ID           string             `json:"id"`
	ProjectID    *string            `json:"project_id"`
	ResourceType string             `json:"resource_type"`
	Limit        int32              `json:"limit"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Resource struct {
	ID             string             `json:"id"`
	ProjectID      string             `json:"project_id"`
	ResourceTypeID string             `json:"resource_type_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Status         string             `json:"status"`
	Spec           []byte             `json:"spec"`
	ProviderRef    string             `json:"provider_ref"`
	StatusMessage  string             `json:"status_message"`
	RequestedBy    string             `json:"requested_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ResourceType struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Category    string             `json:"category"`
	Description string             `json:"description"`
	DefaultSpec []byte             `json:"default_spec"`
	SpecSchema  []byte             `json:"spec_schema"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Team struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TeamMember struct {
	TeamID    string             `json:"team_id"`
	UserID    string             `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	AvatarUrl string             `json:"avatar_url"`
	IssuerSub string             `json:"issuer_sub"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
