// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package db

import (
	"context"
)

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (name, description, scope, project_id, enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, scope, project_id, enabled, created_by, created_at, updated_at
`

type CreatePolicyParams struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Scope       string  `json:"scope"`
	ProjectID   *string `json:"project_id"`
	Enabled     bool    `json:"enabled"`
	CreatedBy   string  `json:"created_by"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.Name,
		arg.Description,
		arg.Scope,
		arg.ProjectID,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.ProjectID,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPolicyRule = `-- name: CreatePolicyRule :one
INSERT INTO policy_rules (policy_id, description, resource_type, attribute, operator, value, effect, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, policy_id, description, resource_type, attribute, operator, value, effect, metadata
`

type CreatePolicyRuleParams struct {
	PolicyID     string `json:"policy_id"`
	Description  string `json:"description"`
	ResourceType string `json:"resource_type"`
	Attribute    string `json:"attribute"`
	Operator     string `json:"operator"`
	Value        string `json:"value"`
	Effect       string `json:"effect"`
	Metadata     []byte `json:"metadata"`
}

func (q *Queries) CreatePolicyRule(ctx context.Context, arg CreatePolicyRuleParams) (PolicyRule, error) {
	row := q.db.QueryRow(ctx, createPolicyRule,
		arg.PolicyID,
		arg.Description,
		arg.ResourceType,
		arg.Attribute,
		arg.Operator,
		arg.Value,
		arg.Effect,
		arg.Metadata,
	)
	var i PolicyRule
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Description,
		&i.ResourceType,
		&i.Attribute,
		&i.Operator,
		&i.Value,
		&i.Effect,
		&i.Metadata,
	)
	return i, err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies WHERE id = $1
`

func (q *Queries) DeletePolicy(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePolicy, id)
	return err
}

const deletePolicyRule = `-- name: DeletePolicyRule :exec
DELETE FROM policy_rules WHERE id = $1
`

func (q *Queries) DeletePolicyRule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePolicyRule, id)
	return err
}

const deletePolicyRulesByPolicy = `-- name: DeletePolicyRulesByPolicy :exec
DELETE FROM policy_rules WHERE policy_id = $1
`

func (q *Queries) DeletePolicyRulesByPolicy(ctx context.Context, policyID string) error {
	_, err := q.db.Exec(ctx, deletePolicyRulesByPolicy, policyID)
	return err
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, name, description, scope, project_id, enabled, created_by, created_at, updated_at FROM policies WHERE id = $1
`

func (q *Queries) GetPolicy(ctx context.Context, id string) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicy, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.ProjectID,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePoliciesForProject = `-- name: ListActivePoliciesForProject :many
SELECT id, name, description, scope, project_id, enabled, created_by, created_at, updated_at FROM policies
WHERE enabled = true AND (scope = 'global' OR project_id = $1)
ORDER BY scope, created_at
`

func (q *Queries) ListActivePoliciesForProject(ctx context.Context, projectID *string) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listActivePoliciesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.ProjectID,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, name, description, scope, project_id, enabled, created_by, created_at, updated_at FROM policies ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListPoliciesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPolicies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.ProjectID,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyRules = `-- name: ListPolicyRules :many
SELECT id, policy_id, description, resource_type, attribute, operator, value, effect, metadata FROM policy_rules WHERE policy_id = $1 ORDER BY resource_type, attribute
`

func (q *Queries) ListPolicyRules(ctx context.Context, policyID string) ([]PolicyRule, error) {
	rows, err := q.db.Query(ctx, listPolicyRules, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyRule{}
	for rows.Next() {
		var i PolicyRule
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Description,
			&i.ResourceType,
			&i.Attribute,
			&i.Operator,
			&i.Value,
			&i.Effect,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies
SET name = $2, description = $3, enabled = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, description, scope, project_id, enabled, created_by, created_at, updated_at
`

type UpdatePolicyParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Enabled,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.ProjectID,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
