// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMembership = `-- name: AddMembership :one
INSERT INTO memberships (user_id, project_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, project_id) DO UPDATE SET role = EXCLUDED.role, updated_at = now()
RETURNING id, user_id, project_id, role, created_at, updated_at
`

type AddMembershipParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
	Role      string `json:"role"`
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, addMembership, arg.UserID, arg.ProjectID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (team_id, name, slug, description)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, name, slug, description, created_at, updated_at
`

type CreateProjectParams struct {
	TeamID      string `json:"team_id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TeamID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, project_id, role, created_at, updated_at FROM memberships WHERE user_id = $1 AND project_id = $2
`

type GetMembershipParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.ProjectID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, team_id, name, slug, description, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, team_id, name, slug, description, created_at, updated_at FROM projects WHERE team_id = $1 AND slug = $2
`

type GetProjectBySlugParams struct {
	TeamID string `json:"team_id"`
	Slug   string `json:"slug"`
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.TeamID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT m.id, m.user_id, m.project_id, m.role, m.created_at, m.updated_at, u.email, u.name AS user_name
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.project_id = $1
ORDER BY m.created_at
`

type ListProjectMembersRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	ProjectID string             `json:"project_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Email     string             `json:"email"`
	UserName  string             `json:"user_name"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID string) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByTeam = `-- name: ListProjectsByTeam :many
SELECT id, team_id, name, slug, description, created_at, updated_at FROM projects WHERE team_id = $1 ORDER BY name LIMIT $2 OFFSET $3
`

type ListProjectsByTeamParams struct {
	TeamID string `json:"team_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListProjectsByTeam(ctx context.Context, arg ListProjectsByTeamParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMembership = `-- name: RemoveMembership :exec
DELETE FROM memberships WHERE user_id = $1 AND project_id = $2
`

type RemoveMembershipParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) RemoveMembership(ctx context.Context, arg RemoveMembershipParams) error {
	_, err := q.db.Exec(ctx, removeMembership, arg.UserID, arg.ProjectID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, slug = $3, description = $4, updated_at = now()
WHERE id = $1
RETURNING id, team_id, name, slug, description, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
