// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provisioning_events.sql

package db

import (
	"context"
)

const createProvisioningEvent = `-- name: CreateProvisioningEvent :one
INSERT INTO provisioning_events (resource_id, type, old_status, new_status, message, detail, actor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, resource_id, type, old_status, new_status, message, detail, actor_id, created_at
`

type CreateProvisioningEventParams struct {
	ResourceID string `json:"resource_id"`
	Type       string `json:"type"`
	OldStatus  string `json:"old_status"`
	NewStatus  string `json:"new_status"`
	Message    string `json:"message"`
	Detail     []byte `json:"detail"`
	ActorID    string `json:"actor_id"`
}

func (q *Queries) CreateProvisioningEvent(ctx context.Context, arg CreateProvisioningEventParams) (ProvisioningEvent, error) {
	row := q.db.QueryRow(ctx, createProvisioningEvent,
		arg.ResourceID,
		arg.Type,
		arg.OldStatus,
		arg.NewStatus,
		arg.Message,
		arg.Detail,
		arg.ActorID,
	)
	var i ProvisioningEvent
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Type,
		&i.OldStatus,
		&i.NewStatus,
		&i.Message,
		&i.Detail,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const listProvisioningEvents = `-- name: ListProvisioningEvents :many
SELECT id, resource_id, type, old_status, new_status, message, detail, actor_id, created_at FROM provisioning_events
WHERE resource_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProvisioningEventsParams struct {
	ResourceID string `json:"resource_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListProvisioningEvents(ctx context.Context, arg ListProvisioningEventsParams) ([]ProvisioningEvent, error) {
	rows, err := q.db.Query(ctx, listProvisioningEvents, arg.ResourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProvisioningEvent{}
	for rows.Next() {
		var i ProvisioningEvent
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Type,
			&i.OldStatus,
			&i.NewStatus,
			&i.Message,
			&i.Detail,
			&i.ActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
