// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddMembership(ctx context.Context, arg AddMembershipParams) (Membership, error)
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	CountResourcesByProjectAndType(ctx context.Context, arg CountResourcesByProjectAndTypeParams) (int64, error)
	CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (ApprovalRequest, error)
	CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditEntry, error)
	CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error)
	CreatePolicyRule(ctx context.Context, arg CreatePolicyRuleParams) (PolicyRule, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProvisioningEvent(ctx context.Context, arg CreateProvisioningEventParams) (ProvisioningEvent, error)
	CreateQuota(ctx context.Context, arg CreateQuotaParams) (Quota, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateResourceType(ctx context.Context, arg CreateResourceTypeParams) (ResourceType, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePolicy(ctx context.Context, id string) error
	DeletePolicyRule(ctx context.Context, id string) error
	DeletePolicyRulesByPolicy(ctx context.Context, policyID string) error
	DeleteProject(ctx context.Context, id string) error
	DeleteQuota(ctx context.Context, id string) error
	DeleteResource(ctx context.Context, id string) error
	DeleteResourceType(ctx context.Context, id string) error
	DeleteTeam(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	ExpireApprovalRequests(ctx context.Context) (int64, error)
	GetApprovalRequest(ctx context.Context, id string) (ApprovalRequest, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetPolicy(ctx context.Context, id string) (Policy, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error)
	GetQuota(ctx context.Context, id string) (Quota, error)
	GetResource(ctx context.Context, id string) (Resource, error)
	GetResourceBySlug(ctx context.Context, arg GetResourceBySlugParams) (Resource, error)
	GetResourceType(ctx context.Context, id string) (ResourceType, error)
	GetResourceTypeBySlug(ctx context.Context, slug string) (ResourceType, error)
	GetTeam(ctx context.Context, id string) (Team, error)
	GetTeamBySlug(ctx context.Context, slug string) (Team, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByIssuerSub(ctx context.Context, issuerSub string) (User, error)
	ListActivePoliciesForProject(ctx context.Context, projectID *string) ([]Policy, error)
	ListAllResourceTypes(ctx context.Context) ([]ResourceType, error)
	ListApprovalRequestsByProject(ctx context.Context, arg ListApprovalRequestsByProjectParams) ([]ApprovalRequest, error)
	ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditEntry, error)
	ListAuditEntriesByActor(ctx context.Context, arg ListAuditEntriesByActorParams) ([]AuditEntry, error)
	ListAuditEntriesByProject(ctx context.Context, arg ListAuditEntriesByProjectParams) ([]AuditEntry, error)
	ListPendingApprovals(ctx context.Context, arg ListPendingApprovalsParams) ([]ApprovalRequest, error)
	ListPendingApprovalsByProject(ctx context.Context, projectID string) ([]ApprovalRequest, error)
	ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]Policy, error)
	ListPolicyRules(ctx context.Context, policyID string) ([]PolicyRule, error)
	ListProjectMembers(ctx context.Context, projectID string) ([]ListProjectMembersRow, error)
	ListProjectsByTeam(ctx context.Context, arg ListProjectsByTeamParams) ([]Project, error)
	ListProvisioningEvents(ctx context.Context, arg ListProvisioningEventsParams) ([]ProvisioningEvent, error)
	ListQuotasForProject(ctx context.Context, projectID *string) ([]Quota, error)
	ListResourceTypes(ctx context.Context) ([]ResourceType, error)
	ListResourcesByProject(ctx context.Context, arg ListResourcesByProjectParams) ([]Resource, error)
	ListResourcesByStatus(ctx context.Context, arg ListResourcesByStatusParams) ([]Resource, error)
	ListTeamMembers(ctx context.Context, teamID string) ([]ListTeamMembersRow, error)
	ListTeams(ctx context.Context, arg ListTeamsParams) ([]Team, error)
	ListTeamsForUser(ctx context.Context, userID string) ([]Team, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveMembership(ctx context.Context, arg RemoveMembershipParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	ReviewApprovalRequest(ctx context.Context, arg ReviewApprovalRequestParams) (ApprovalRequest, error)
	SetResourceProviderRef(ctx context.Context, arg SetResourceProviderRefParams) error
	UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateQuota(ctx context.Context, arg UpdateQuotaParams) (Quota, error)
	UpdateResourceSpec(ctx context.Context, arg UpdateResourceSpecParams) (Resource, error)
	UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error)
	UpdateResourceType(ctx context.Context, arg UpdateResourceTypeParams) (ResourceType, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
