// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotas.sql

package db

import (
	"context"
)

const createQuota = `-- name: CreateQuota :one
INSERT INTO quotas (project_id, resource_type, "limit")
VALUES ($1, $2, $3)
RETURNING id, project_id, resource_type, "limit", created_at, updated_at
`

type CreateQuotaParams struct {
	ProjectID    *string `json:"project_id"`
	ResourceType string  `json:"resource_type"`
	Limit        int32   `json:"limit"`
}

func (q *Queries) CreateQuota(ctx context.Context, arg CreateQuotaParams) (Quota, error) {
	row := q.db.QueryRow(ctx, createQuota, arg.ProjectID, arg.ResourceType, arg.Limit)
	var i Quota
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceType,
		&i.Limit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuota = `-- name: DeleteQuota :exec
DELETE FROM quotas WHERE id = $1
`

func (q *Queries) DeleteQuota(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteQuota, id)
	return err
}

const getQuota = `-- name: GetQuota :one
SELECT id, project_id, resource_type, "limit", created_at, updated_at FROM quotas WHERE id = $1
`

func (q *Queries) GetQuota(ctx context.Context, id string) (Quota, error) {
	row := q.db.QueryRow(ctx, getQuota, id)
	var i Quota
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceType,
		&i.Limit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuotasForProject = `-- name: ListQuotasForProject :many
SELECT id, project_id, resource_type, "limit", created_at, updated_at FROM quotas
WHERE project_id = $1 OR project_id IS NULL
ORDER BY project_id NULLS LAST, resource_type
`

func (q *Queries) ListQuotasForProject(ctx context.Context, projectID *string) ([]Quota, error) {
	rows, err := q.db.Query(ctx, listQuotasForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quota{}
	for rows.Next() {
		var i Quota
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ResourceType,
			&i.Limit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuota = `-- name: UpdateQuota :one
UPDATE quotas
SET "limit" = $2, updated_at = now()
WHERE id = $1
RETURNING id, project_id, resource_type, "limit", created_at, updated_at
`

type UpdateQuotaParams struct {
	ID    string `json:"id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) UpdateQuota(ctx context.Context, arg UpdateQuotaParams) (Quota, error) {
	row := q.db.QueryRow(ctx, updateQuota, arg.ID, arg.Limit)
	var i Quota
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceType,
		&i.Limit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
