// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_types.sql

package db

import (
	"context"
)

const createResourceType = `-- name: CreateResourceType :one
INSERT INTO resource_types (name, slug, category, description, default_spec, spec_schema, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, slug, category, description, default_spec, spec_schema, enabled, created_at, updated_at
`

type CreateResourceTypeParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Category    string `json:"category"`
	Description string `json:"description"`
	DefaultSpec []byte `json:"default_spec"`
	SpecSchema  []byte `json:"spec_schema"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) CreateResourceType(ctx context.Context, arg CreateResourceTypeParams) (ResourceType, error) {
	row := q.db.QueryRow(ctx, createResourceType,
		arg.Name,
		arg.Slug,
		arg.Category,
		arg.Description,
		arg.DefaultSpec,
		arg.SpecSchema,
		arg.Enabled,
	)
	var i ResourceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.DefaultSpec,
		&i.SpecSchema,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResourceType = `-- name: DeleteResourceType :exec
DELETE FROM resource_types WHERE id = $1
`

func (q *Queries) DeleteResourceType(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteResourceType, id)
	return err
}

const getResourceType = `-- name: GetResourceType :one
SELECT id, name, slug, category, description, default_spec, spec_schema, enabled, created_at, updated_at FROM resource_types WHERE id = $1
`

func (q *Queries) GetResourceType(ctx context.Context, id string) (ResourceType, error) {
	row := q.db.QueryRow(ctx, getResourceType, id)
	var i ResourceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.DefaultSpec,
		&i.SpecSchema,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceTypeBySlug = `-- name: GetResourceTypeBySlug :one
SELECT id, name, slug, category, description, default_spec, spec_schema, enabled, created_at, updated_at FROM resource_types WHERE slug = $1
`

func (q *Queries) GetResourceTypeBySlug(ctx context.Context, slug string) (ResourceType, error) {
	row := q.db.QueryRow(ctx, getResourceTypeBySlug, slug)
	var i ResourceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.DefaultSpec,
		&i.SpecSchema,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllResourceTypes = `-- name: ListAllResourceTypes :many
SELECT id, name, slug, category, description, default_spec, spec_schema, enabled, created_at, updated_at FROM resource_types ORDER BY category, name
`

func (q *Queries) ListAllResourceTypes(ctx context.Context) ([]ResourceType, error) {
	rows, err := q.db.Query(ctx, listAllResourceTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceType{}
	for rows.Next() {
		var i ResourceType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.Description,
			&i.DefaultSpec,
			&i.SpecSchema,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceTypes = `-- name: ListResourceTypes :many
SELECT id, name, slug, category, description, default_spec, spec_schema, enabled, created_at, updated_at FROM resource_types WHERE enabled = true ORDER BY category, name
`

func (q *Queries) ListResourceTypes(ctx context.Context) ([]ResourceType, error) {
	rows, err := q.db.Query(ctx, listResourceTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceType{}
	for rows.Next() {
		var i ResourceType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.Description,
			&i.DefaultSpec,
			&i.SpecSchema,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResourceType = `-- name: UpdateResourceType :one
UPDATE resource_types
SET name = $2, slug = $3, category = $4, description = $5,
    default_spec = $6, spec_schema = $7, enabled = $8, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, category, description, default_spec, spec_schema, enabled, created_at, updated_at
`

type UpdateResourceTypeParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Category    string `json:"category"`
	Description string `json:"description"`
	DefaultSpec []byte `json:"default_spec"`
	SpecSchema  []byte `json:"spec_schema"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) UpdateResourceType(ctx context.Context, arg UpdateResourceTypeParams) (ResourceType, error) {
	row := q.db.QueryRow(ctx, updateResourceType,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Category,
		arg.Description,
		arg.DefaultSpec,
		arg.SpecSchema,
		arg.Enabled,
	)
	var i ResourceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.DefaultSpec,
		&i.SpecSchema,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
