// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package db

import (
	"context"
)

const countResourcesByProjectAndType = `-- name: CountResourcesByProjectAndType :one
SELECT count(*) FROM resources
WHERE project_id = $1 AND resource_type_id = $2 AND status NOT IN ('deleted', 'failed')
`

type CountResourcesByProjectAndTypeParams struct {
	ProjectID      string `json:"project_id"`
	ResourceTypeID string `json:"resource_type_id"`
}

func (q *Queries) CountResourcesByProjectAndType(ctx context.Context, arg CountResourcesByProjectAndTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResourcesByProjectAndType, arg.ProjectID, arg.ResourceTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (project_id, resource_type_id, name, slug, status, spec, requested_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, resource_type_id, name, slug, status, spec, provider_ref, status_message, requested_by, created_at, updated_at
`

type CreateResourceParams struct {
	ProjectID      string `json:"project_id"`
	ResourceTypeID string `json:"resource_type_id"`
	Name           string `json:"name"`
	Slug           string `json:"slug"`
	Status         string `json:"status"`
	Spec           []byte `json:"spec"`
	RequestedBy    string `json:"requested_by"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.ProjectID,
		arg.ResourceTypeID,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.Spec,
		arg.RequestedBy,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceTypeID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Spec,
		&i.ProviderRef,
		&i.StatusMessage,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, project_id, resource_type_id, name, slug, status, spec, provider_ref, status_message, requested_by, created_at, updated_at FROM resources WHERE id = $1
`

func (q *Queries) GetResource(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceTypeID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Spec,
		&i.ProviderRef,
		&i.StatusMessage,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceBySlug = `-- name: GetResourceBySlug :one
SELECT id, project_id, resource_type_id, name, slug, status, spec, provider_ref, status_message, requested_by, created_at, updated_at FROM resources WHERE project_id = $1 AND slug = $2
`

type GetResourceBySlugParams struct {
	ProjectID string `json:"project_id"`
	Slug      string `json:"slug"`
}

func (q *Queries) GetResourceBySlug(ctx context.Context, arg GetResourceBySlugParams) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceBySlug, arg.ProjectID, arg.Slug)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceTypeID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Spec,
		&i.ProviderRef,
		&i.StatusMessage,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResourcesByProject = `-- name: ListResourcesByProject :many
SELECT id, project_id, resource_type_id, name, slug, status, spec, provider_ref, status_message, requested_by, created_at, updated_at FROM resources WHERE project_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListResourcesByProjectParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListResourcesByProject(ctx context.Context, arg ListResourcesByProjectParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ResourceTypeID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.Spec,
			&i.ProviderRef,
			&i.StatusMessage,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByStatus = `-- name: ListResourcesByStatus :many
SELECT id, project_id, resource_type_id, name, slug, status, spec, provider_ref, status_message, requested_by, created_at, updated_at FROM resources
WHERE status = $1
ORDER BY updated_at ASC
LIMIT $2 OFFSET $3
`

type ListResourcesByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListResourcesByStatus(ctx context.Context, arg ListResourcesByStatusParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ResourceTypeID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.Spec,
			&i.ProviderRef,
			&i.StatusMessage,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResourceProviderRef = `-- name: SetResourceProviderRef :exec
UPDATE resources SET provider_ref = $2, updated_at = now() WHERE id = $1
`

type SetResourceProviderRefParams struct {
	ID          string `json:"id"`
	ProviderRef string `json:"provider_ref"`
}

func (q *Queries) SetResourceProviderRef(ctx context.Context, arg SetResourceProviderRefParams) error {
	_, err := q.db.Exec(ctx, setResourceProviderRef, arg.ID, arg.ProviderRef)
	return err
}

const updateResourceSpec = `-- name: UpdateResourceSpec :one
UPDATE resources
SET spec = $2, updated_at = now()
WHERE id = $1
RETURNING id, project_id, resource_type_id, name, slug, status, spec, provider_ref, status_message, requested_by, created_at, updated_at
`

type UpdateResourceSpecParams struct {
	ID   string `json:"id"`
	Spec []byte `json:"spec"`
}

func (q *Queries) UpdateResourceSpec(ctx context.Context, arg UpdateResourceSpecParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResourceSpec, arg.ID, arg.Spec)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceTypeID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Spec,
		&i.ProviderRef,
		&i.StatusMessage,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateResourceStatus = `-- name: UpdateResourceStatus :one
UPDATE resources
SET status = $2, status_message = $3, updated_at = now()
WHERE id = $1
RETURNING id, project_id, resource_type_id, name, slug, status, spec, provider_ref, status_message, requested_by, created_at, updated_at
`

type UpdateResourceStatusParams struct {
	ID            string `json:"id"`
	Status        string `json:"status"`
	StatusMessage string `json:"status_message"`
}

func (q *Queries) UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResourceStatus, arg.ID, arg.Status, arg.StatusMessage)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceTypeID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Spec,
		&i.ProviderRef,
		&i.StatusMessage,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
